import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faEye,
  faEyeSlash,
  faBell,
  faEdit,
  faTrashAlt,
  faImage,
} from '@fortawesome/free-regular-svg-icons';
import {
  faEnvelope,
  faLock,
  faUser,
  faUserCircle,
  faSignOutAlt,
  faUserCog,
  faShoppingBag,
  faAngleDown,
  faFileAlt,
  faTag,
  faPlus,
  faArrowLeft,
  faAngleRight,
  faAngleLeft,
  faArrowDown,
  faDollarSign,
  faCheck,
  faTimes,
} from '@fortawesome/free-solid-svg-icons';

const icons = [
  faEye,
  faEyeSlash,
  faEnvelope,
  faLock,
  faUser,
  faArrowLeft,
  faUserCircle,
  faSignOutAlt,
  faAngleRight,
  faUserCog,
  faBell,
  faShoppingBag,
  faAngleDown,
  faFileAlt,
  faTag,
  faEdit,
  faTrashAlt,
  faPlus,
  faAngleLeft,
  faArrowDown,
  faDollarSign,
  faCheck,
  faUserCircle,
  faTimes,
  faImage,
];

library.add(...icons);
