import { library } from '@fortawesome/fontawesome-svg-core';
import { faGithub, faBloggerB } from '@fortawesome/free-brands-svg-icons';
import {
  faEye,
  faEyeSlash,
  faBell,
  faEdit,
  faTrashAlt,
  faMoneyBillAlt,
} from '@fortawesome/free-regular-svg-icons';
import {
  faEnvelope,
  faLock,
  faUser,
  faUserCircle,
  faSignOutAlt,
  faShoppingBag,
  faAngleDown,
  faFileAlt,
  faTag,
  faPlus,
  faMinus,
  faArrowLeft,
  faAngleRight,
  faAngleLeft,
  faArrowDown,
  faDollarSign,
  faCheck,
  faTimes,
  faBan,
  faExclamation,
  faExchangeAlt,
  faShoppingCart,
  faSearch,
  faCartArrowDown,
  faCube,
  faPen,
  faShippingFast,
  faMoneyBillWave,
  faMoneyCheck,
  faUserEdit,
} from '@fortawesome/free-solid-svg-icons';

const icons = [
  faEye,
  faEyeSlash,
  faEnvelope,
  faLock,
  faUser,
  faArrowLeft,
  faUserCircle,
  faSignOutAlt,
  faAngleRight,
  faBell,
  faShoppingBag,
  faAngleDown,
  faFileAlt,
  faTag,
  faEdit,
  faTrashAlt,
  faPlus,
  faMinus,
  faAngleLeft,
  faArrowDown,
  faDollarSign,
  faCheck,
  faTimes,
  faBan,
  faExclamation,
  faExchangeAlt,
  faShoppingCart,
  faSearch,
  faCartArrowDown,
  faGithub,
  faBloggerB,
  faCube,
  faPen,
  faShippingFast,
  faMoneyBillWave,
  faMoneyBillAlt,
  faMoneyCheck,
  faUserEdit,
];

library.add(...icons);
